apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobblerweb
  labels:
    app: gobbler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gobbler
  template:
    metadata:
      labels:
        app: gobbler
        tier: web
    spec:
      containers:
        - name: gobbler-app
          image: gcr.io/knife-ceramic-236502/gobbler:release-1.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: env-configmap
            - configMapRef:
                name: env-secrets
